### PR TITLE
Enable install only if main project

### PR DESCRIPTION
**Pull request by LucaCiucci**

### CODE REVIEW

**Comment by SpartanJ** [comment]
Hi, sorry but I'm not versed in CMake at all. What does exactly this change? How it behaved and how it behaves with the change?

**Comment by LucaCiucci** [comment]
Sorry for the missing description.

Consider a dependent project that downloads and include this library, for example:
```cmake
FetchContent_Declare(
	efsw
	GIT_REPOSITORY https://github.com/SpartanJ/efsw
)
FetchContent_MakeAvailable(efsw)
```
which might provide some install targets. When the dependant project is installed, it will also install esfw by default, but this might be an unwanted behaviour.

The lines:
```cmake
set(ESFW_MAIN_PROJECT FALSE)
if ((CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR) AND (CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME))
  set(ESFW_MAIN_PROJECT TRUE)
endif()
```
check if this is the main project by comparing the top level project name (`CMAKE_PROJECT_NAME`) and the current project name (`PROJECT_NAME` that in this case is "efsw"), the same is done for the source dir.

At this point if this is the main project, we will enable all the installing stuff.

I'm now wondering if this is the best thing to do, maybe a better solution would be to just set the default value of (`EFSW_INSTALL`) to false when not the main project?

**Comment by SpartanJ** [comment]
> I'm now wondering if this is the best thing to do, maybe a better solution would be to just set the default value of (EFSW_INSTALL) to false when not the main project?

I think that's the correct solution. The flag is there for that reason. I don't know how CMake dependencies work, you can't just set the flag from the main project avoiding any change to the efsw `CMakeLists.txt` file?

**Comment by LucaCiucci** [comment]
Yes, you can set the flag from the main project or set the option by hand, but disabling install by defualt when not the main project would make is easier to depend on efsw. I think a good example is presented in [yaml-cpp](https://github.com/jbeder/yaml-cpp/blob/1b50109f7bea60bd382d8ea7befce3d2bd67da5f/CMakeLists.txt#L25):
```cmake
option(YAML_CPP_INSTALL "Enable generation of yaml-cpp install targets" ${YAML_CPP_MAIN_PROJECT})
```

**Comment by SpartanJ** [comment]
Sounds reasonable, thanks.

**Pull request merged**
